<?php
// module/Anketa/view/anketa/anketa/index.phtml:

$title = 'Анкеты клиенток';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('ankenta', ['action' => 'create']) ?>">Заполнить анкету</a>
</p>

<table class="table">
    <tr>
        <th>Фамилия и имя</th>
        <th>Возраст</th>
        <th>Вес, кг</th>
        <th>Рост, см</th>
        <th>Дата старта</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($anketa->last_name) ?> <?= $this->escapeHtml($anketa->first_name) ?></td>
            <td><?= $this->escapeHtml($anketa->age) ?></td>
            <td><?= $this->escapeHtml($anketa->weight) ?></td>
            <td><?= $this->escapeHtml($anketa->height) ?></td>
            <td><?= $this->escapeHtml($anketa->date_start) ?></td>
            <td>
                <a href="<?= $this->url('anketa', ['action' => 'edit', 'id' => $anketa->id]) ?>">Редактировать</a>
                <a href="<?= $this->url('anketa', ['action' => 'delete', 'id' => $anketa->id]) ?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>